### PR TITLE
Improved Github Action by adding code coverage

### LINKED ISSUE #7: coveralls
I ran into an issue while setting up Coveralls with GH Actions. giving up for now.

See this issue: php-coveralls/php-coveralls#339

### PR DESCRIPTION
**Pull request by adrenalinkin**
Closes #7

### CODE REVIEW

**Comment by adrenalinkin** [comment]
@dakujem allow to run pipeline please
This working fine, you can check this out here https://coveralls.io/github/adrenalinkin/oliva-tree

**Comment by adrenalinkin** [comment]
@dakujem I can return badge into documentation before merge.

**Comment by adrenalinkin** [comment]
@dakujem I faced some strange behavior - we sent report with `tests` coverage instead `src`
Any idea how is it possible? locally i cant reproduce it.
Maybe this is some specific behavior  of the `nette/tester` ?
изображение

**Comment by adrenalinkin** [comment]
Last commit fix the issue with incorrect coverage report

**Comment by dakujem** [comment]
Great. Thanks a lot for all the work. Sure, you can return the badge now.

**Comment by adrenalinkin** [comment]
@dakujem Watch above. Already badge already returned, so PR ready to merge

**Comment by dakujem** [comment]
My bad. You _removed_ the comments around the badge. Seeing the diff, I thought you added them.

**Comment by dakujem** [comment]
Merged. Thank you a lot, Viktor.

**Pull request closed without merging**
